wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712520428.608549
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 15
      - 23
      4: 3.11.6
      5: 0.16.3
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
