wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713290007.454964
    t:
      1:
      - 55
      3:
      - 13
      - 15
      - 23
      4: 3.11.4
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
